- alumnos/yah.txt
El maestro nos pidió que agregáramos un archivo con nuestro nombre y aquí esta
> Agregar un archivo con mi nombre

- alumnos/extra/comandos-git.txt
- alumnos/mbm.txt
> Nombres y archivos

- alumnos/IDLT.txt
- alumnos/extra/git-config.txt
El maestro nos pidio que agregaramos un archivo con nuestro nombre y aqui esta.
> Agregar un archivo con un nombre

- alumnos/pafa.txt
El maestro nos pidio que hicieramos un archivo con mi nombre y aquí esta. Lo que hicimos en la clase
> Agragar un archivo con mi nombre

- 240113427/test1.py
- alumnos/AAON.txt
nombre y mi nombre dentro del mismo
Agragar un archivo python donde estuve realizando pruebas
>  Agregar un archivo txt con mis iniciales como

- alumnos/hagm.txt
Miguelinux nos pidió agregar un archivo con nuestro nombre.
> Agregar archivo con mi nombre

- alumnos/pafa/tarea-numeros.py
El profesor le pidió a los alumnos realizar un programa que se le puedan ingresar números y que regrese el mismo pero escrito en números. Después se debe subir el programa al repositorio ayda24 para concluir la actividad
Pablo Alejandro Fletes Alvarado
> Tarea programa de numeros

- alumnos/OscarGM/Tarea.py
Se creo un programa en python que se ingresa un numero y regresa su valor en letras
> Agregar un archivo que convierte números a letras

- alumnos/IDLT/numeros.py
La tarea de números convertidos a su forma de escribir.
> Tarea de los numeros a letras

- alumnos/gah/numeros_a_texto.py
Agregar código de python para convertir números a letra
> Números a letra

- alumnos/jmbv.txt
El profe me hizo poner un archivo con mi nombre
> Agregando archivo con mi nombre

- alumnos/JGS/numero_texto.py
Agregar tarea de numeros a texto
> JesusGarcia

- alumnos/HAGM/num_to_text.py
- alumnos/hagm.txt
Ya debe tener mi nombre real :D
> Nombre y numero a texto con nuevo author

- alumnos/aur.txt
este es un test para un commint
> Archivo con mi monbre

- 241102/v3/insercion.py
> inserción v3

- 241102/v1/seleccion.py
Agregar algoritmo de selección en la carpeta v1
> Algoritmo de selección

- 241102/v2/insercion.py
Archivo modificado con ejemplo de ordenamiento Inserción
> Insercion python

- 241123/pafa.py
El profesor nos solicito realizar las busquedas lineales y binarias en un mismo archivo, y subirlo al repositorio ayda24.
> Algoritmos de busqueda lineal y busqueda

- 241123/JGS.txt
Tarea busqueda lineal y binaria
> Tarea Jesus Garcia

- 241123/IDLT.py
Codigo en python para busqueda lineal y busqueda binaria con mis iniciales.
> Busquedas lineal y binaria

- 241123/GAH-busqueda.py
Implementar el algoritmo de búsqueda lineal y binaria.
> Algoritmos de busqueda
